name: CI (linux-only, analyze & test)

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - "*.txt"
      - "LICENSE"
      - ".github/**"
  push:
    branches: [ main ]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - "*.txt"
      - "LICENSE"
      - ".github/**"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter analyze
        run: flutter analyze
      - name: Flutter tests
        run: flutter test --coverage
      - name: Upload coverage (short retention)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 2
