name: Scaffold Flutter app

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App name (e.g., ytdlp)"
        required: true
        default: "ytdlp"
      org_name:
        description: "Organization identifier (reverse-DNS, e.g., com.example)"
        required: true
        default: "com.ruzamin.ytdlp"

permissions:
  contents: write

concurrency:
  group: scaffold-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Create Flutter app (if absent)
        run: |
          if [ -f "pubspec.yaml" ]; then
            echo "Flutter project already exists. Skipping scaffold."; exit 0; fi
          flutter --version
          flutter config --no-analytics
          flutter create . --platforms=macos,ios,android,web,windows,linux \
            --org "${{ github.event.inputs.org_name }}" \
            --project-name "$(echo "${{ github.event.inputs.app_name }}" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]_')"
          flutter pub get
      - name: Commit scaffold
        run: |
          if git diff --quiet; then echo "No changes to commit."; exit 0; fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Scaffold Flutter app: ${{ github.event.inputs.app_name }}"
          git push
